export const AUTH_SERVICE = "AUTH_SERVICE";
export const MYSQL_SERVICE = "MYSQL_SERVICE";
export const USER_SERVICE = "USER_SERVICE";
export const COURSE_SERVICE = "COURSE_SERVICE";
export const MONG0DB_SERVICE = "MONG0DB_SERVICE";

export const UNAUTHORIZED = "UNAUTHORIZED";
export const FORBIDDEN = "FORBIDDEN";
